# Generated by Django 5.2.1 on 2025-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremasApp', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Herramientas Manuales', 'Herramientas Manuales'), ('Herramientas Electricas', 'Herramientas Eléctricas'), ('Materiales Basicos', 'Materiales Básicos'), ('Acabados', 'Acabados'), ('Equipos de Seguridad', 'Equipos de Seguridad'), ('Tornillos y Anclajes', 'Tornillos y Anclajes'), ('Fijaciones y Adhesivos', 'Fijaciones y Adhesivos'), ('Equipos de Medicion', 'Equipos de Medición')], default='Herramientas Manuales', help_text='Categoría del producto', max_length=100),
        ),
    ]
