# Generated by Django 5.2.3 on 2025-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremasApp', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
