# Generated by Django 5.2.3 on 2025-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremasApp', '0004_alter_contacto_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
