# Generated by Django 5.2.1 on 2025-06-16 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_imagen'),
        ('ferremasApp', '0005_delete_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('total', models.IntegerField(verbose_name='Monto Total')),
                ('buy_order', models.CharField(max_length=50, unique=True, verbose_name='Orden de Compra (Transbank)')),
                ('transbank_token', models.CharField(max_length=100, verbose_name='Token de Transbank')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Boleta de Compra',
                'verbose_name_plural': 'Boletas de Compra',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario al Comprar')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ferremasApp.boleta', verbose_name='Boleta Asociada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Boleta',
                'verbose_name_plural': 'Detalles de Boleta',
                'unique_together': {('boleta', 'producto')},
            },
        ),
    ]
