# Generated by Django 5.2.1 on 2025-06-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_imagen'),
        ('ferremasApp', '0006_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Autorización'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='card_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 Dígitos Tarjeta'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producto', verbose_name='Producto'),
        ),
    ]
