"""
Django settings for ferremas project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# from dotenv import load_dotenv # Descomentar si decides usar .env en el futuro
# load_dotenv() # Descomentar si decides usar .env en el futuro

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w-myf6jf)dn%$+e*2-h-wrt7!(nr*&732=tv5t$@yjr+wof2vk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    # Si estás usando Ngrok para probar Transbank localmente,
    # añade aquí tu URL de Ngrok (ej. 'abcdef123456.ngrok-free.app')
    # Por ejemplo: 'your-ngrok-subdomain.ngrok-free.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ferremasApp',
    'api',
    'django.contrib.humanize', # Añadido 'django.contrib.humanize' para formatos de número
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ferremas.urls'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ferremasApp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages', # Esta es la única línea para mensajes
            ],
        },
    },
]

WSGI_APPLICATION = 'ferremas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ferremas_db',
        'USER': 'root',
        'PASSWORD': 'Coco.1630',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Si estás utilizando un modelo de usuario personalizado (ej. CustomUser)
# en tu aplicación 'ferremasApp', descomenta y ajusta la siguiente línea:
# AUTH_USER_MODEL = 'ferremasApp.CustomUser'
# Si no lo estás usando, déjala comentada.


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ferremasApp', 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================================================================
# Transbank Configuration (Ambiente de Integración)
# ====================================================================
# ATENCIÓN: Estas claves son para el ambiente de INTEGRACIÓN/PRUEBAS.
# NO USAR EN PRODUCCIÓN. Para producción, debes obtener las claves reales de Transbank
# e idealmente cargarlas desde variables de entorno (ej. usando python-dotenv).

TBK_API_KEY_ID = '597055555532'
TBK_API_KEY_SECRET = '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
TBK_ENVIRONMENT = 'INTEGRATION' # <--- ¡CORREGIDO A 'INTEGRATION' sin 'N' para que coincida con el error!


TBK_API_BASE_URL = 'https://webpay3g.transbank.cl/rswebpayTransaction/api/webpay/v1.2'


# ====================================================================
# CMF API Configuration (Valor Dólar)
# ====================================================================

URL_BASE_CMF = "https://api.cmfchile.cl/api-sbifv3/recursos_api" # Ajustada a una URL más común para v3
API_KEY_CMF = "793d989c2c3b0987eb56404ed529a24910086f80"